### ISSUE TITLE
Testing IEs

### ISSUE THREAD

**Issue by ghost** [benjamingr/favicon-bug#5]
IE11 on Win7 crashed my system completely.

More details later when I can test properly (or someone else, feel free!)

**Comment by benjamingr** [comment]
Thanks for reporting! When you're done testing please make a pull request and update the readme :)

**Comment by ghost** [comment]
I just tested IE_7_. It's not vulnerable, surprisingly - what would you need in a pull for this? More tests later. 

Edit: I mean examples of updates for both vulnerable and non-vulnerable browsers.

**Comment by benjamingr** [comment]
Not yet, when you're done testing let me know.

**Comment by ghost** [comment]
IE7 on Vista - no problem, memory usage loading the page was ~10mb. No impact on system.
IE8 on XP - crashes in iedevtoolbar.dll after Writing Poc ~1300

My net connection is slow as hell, so I might not try any more.

**Comment by benjamingr** [comment]
Hehe, got to love the fact IE7 is the one that gets it right.

**Comment by yuan3y** [comment]
IE 11 and Project Spartan on Windows 10 build 10074 (running on virtual machine) do not suffer from crashes. Disk usage and net traffic of about 80MB/s (my download bandwidth) sustained for around 50 seconds (Poc = ~100,000), a small amount of traffic of about 1MB/s is observed for around 1 minute (Poc increases at the same rate), afterwards no net traffic is observed, but the Poc number continue to rise. For the above result, nodejs is run on a remote server instead of localhost.

For nodejs running on my localhost, the task manager in the virtual machines shows a very high CPU usage due to System Interrupts, making system very slow to the extent of almost unusable, the Poc increases slowly (~500 by one minute).
